{% set name = "torchkbnufft" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f10aebc6518960aed6ed3c3f16a8f3bb5c9f89e3491c5a275d13297d43037008
  patches:
    # lets tests pass with numpy 2.0, see https://github.com/mmuckley/torchkbnufft/pull/100
    # Todo: remove patch once https://github.com/mmuckley/torchkbnufft/pull/100 is released upstream
    - patches/0001-conftest-np-2-0.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm >=6.3.2
    - setuptools >=59.5.0
    - wheel >=0.37.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22.4,<3.0a0
    - scipy >=1.8.1,<2.0a0
    - pytorch >=1.12,<3.0a0

test:
  imports:
    - torchkbnufft
  source_files:
    - tests
    - notebooks
  commands:
    - pip check
    - pytest tests
    # omits Toeplitz Example: pytorch 2.0, see https://github.com/mmuckley/torchkbnufft/issues/98
    - pytest --nbmake "notebooks/Basic Example.ipynb" "notebooks/SENSE Example.ipynb" "notebooks/Sparse Matrix Example.ipynb"
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - matplotlib
    - nbmake

about:
  summary: A high-level, easy-to-deploy non-uniform Fast Fourier Transform in PyTorch.
  home: https://github.com/mmuckley/torchkbnufft
  dev_url: https://github.com/mmuckley/torchkbnufft
  doc_url: https://torchkbnufft.readthedocs.io/en/stable/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mmuckley
    - gabuzi
